### ISSUE TITLE
OpenTelemetry: Automatic context propagation is broken for spans that invoke `Unsafe`

### ISSUE THREAD

**Issue by seveneves** [zio/zio-telemetry#975]
I have a ZIO based app that is using automatic instrumentation via JVM agent. The app has layers of interoperability between direct Scala and ZIO effects. 

I noticed that context propagation is broken in case when there is an `Unsafe` invocation on a ZIO effect. The problem is highlighted with the following code.

```scala
  @io.opentelemetry.instrumentation.annotations.WithSpan
  private def handler(): Unit =
    println(span("Before"))
    ZIO.attempt(s"unsafely-executed").unsafeRun
    println(span("After"))

  private def span(name: String) =
    val ctx = Span.current().getSpanContext
    s"$name VALID: ${ctx.isValid}, ${ctx.getSpanId}"
```

when it is executed with `ZIO.attempt(handler())` the following output is produced 

```
Before VALID: true, b0839dd0b2bf9277
After VALID: false, 0000000000000000
```

Here is full scala cli source that just needs a correct path to the java agent 

```
cs fetch --classpath "io.opentelemetry.javaagent:opentelemetry-javaagent:2.15.0"
```

copy the path and paste it over `/path/to/opentelemetry-javaagent-2.15.0.jar` in the following code

```scala
//> using dep io.opentelemetry.instrumentation:opentelemetry-instrumentation-annotations:2.15.0
//> using dep dev.zio::zio:2.1.17
//> using scala 3.6.4
//> using javaOpt -Dotel.traces.exporter=console -Dotel.metrics.exporter=none -javaagent:/path/to/opentelemetry-javaagent-2.15.0.jar

import io.opentelemetry.api.GlobalOpenTelemetry
import io.opentelemetry.api.trace.{Span, SpanKind}
import zio.*

object Run extends ZIOAppDefault:

  override def run = ZIO.attempt(handler())

  @io.opentelemetry.instrumentation.annotations.WithSpan
  private def handler(): Unit =
    println(span("Before"))
    ZIO.attempt(s"unsafely-executed").unsafeRun
    println(span("After"))

  private def span(name: String) =
    val ctx = Span.current().getSpanContext
    s"$name VALID: ${ctx.isValid}, ${ctx.getSpanId}"

  extension [E, A](effect: ZIO[Any, Throwable, A])
    private def unsafeRun(using E <:< Throwable): A = Unsafe.unsafe:
      implicit unsafe => runtime.unsafe.run(effect).getOrThrow()
```

**Comment by grouzen** [comment]
Hi! Thanks for reporting. I tried to run it with [ZIO instrumentation](https://github.com/open-telemetry/opentelemetry-java-instrumentation/tree/main/instrumentation/zio/zio-2.0/javaagent) disabled by adding `-Dotel.instrumentation.zio.enabled=false` option and the problem is gone. 
The current version of ZIO instrumentation is broken on so many levels. I'm currently working on fixing it but it is not an easy task.

**Comment by seveneves** [comment]
@grouzen thank you for the suggestion! It indeed works with `-Dotel.instrumentation.zio.enabled=false`. 

The situation is a bit more complex in my app compared to the example I posted. There is also usage of `zio.telemetry.opentelemetry.OpenTelemetry.global ++ zio.telemetry.opentelemetry.OpenTelemetry.contextJVM` from `dev.zio:zio-opentelemetry` to have custom traces in zio effects. 

Should I still use `contextJVM` or `contextZIO` with `-Dotel.instrumentation.zio.enabled=false`?

**Comment by grouzen** [comment]
In general, it should be enough to have one instance of OpenTelemetry in an application unless you have a very peculiar case and you understand why and what you're doing. So, in your case, I would suggest using `OpenTelemetry.global` + `OpenTelemetry.contextJVM`. This scenario implies that you are using auto instrumentation (opentelemetry-javaagent) so you don't need to disable ZIO instrumentation. Bug again, given your example, you will end up with a broken Context if you need to run an unsafe ZIO piece of logic. I can't say right now why it happens. I'm hoping to fix it by getting rid of the current ZIO instrumentation. 
You can find a bit more details on this in https://github.com/zio/zio-telemetry/pull/924.

**Comment by grouzen** [comment]
Also, you can follow my progress on fixing it in https://github.com/zio/zio-telemetry/pull/976

**Comment by seveneves** [comment]
@grouzen Thank you!

just letting you know that `-Dotel.instrumentation.zio.enabled=false` had a decremental effect on linking spans together into the same trace

**Comment by grouzen** [comment]
@seveneves Hey! I've just merged https://github.com/zio/zio-telemetry/pull/976. Could you please try it and let me know how it works for your case? It is available in the version https://github.com/zio/zio-telemetry/releases/tag/v4.0.0-RC1
Please don't hesitate to ask me if you need help with the new version.

**Comment by seveneves** [comment]
@grouzen 

the problem is still there. Here are my dependencies. 

```scala
//> using dep io.opentelemetry.instrumentation:opentelemetry-instrumentation-annotations:2.15.0
//> using dep dev.zio::zio:2.1.17
//> using dep dev.zio::zio-opentelemetry:4.0.0-RC2
//> using scala 3.6.4
//> using javaOpt -Dotel.traces.exporter=console -Dotel.metrics.exporter=none -javaagent:/Users/xxx/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/io/opentelemetry/javaagent/opentelemetry-javaagent/2.15.0/opentelemetry-javaagent-2.15.0.jar

import io.opentelemetry.api.trace.Span
import zio.*
import zio.telemetry.opentelemetry.OpenTelemetry
import zio.telemetry.opentelemetry.trace.Tracer

object Run extends ZIOAppDefault:

  override def run = ZIO.attempt(unsafe()).traced("root")

  private def unsafe(): Unit =
    println(currentSpan("Before"))
    ZIO.attempt(s"unsafely-executed").unsafeRun
    println(currentSpan("After"))

  private def currentSpan(name: String) =
    val ctx = Span.current().getSpanContext
    s"$name VALID: ${ctx.isValid}, ${ctx.getSpanId}"

  extension [E, A](effect: ZIO[Any, E, A])
    private def unsafeRun(using E <:< Throwable): A = Unsafe.unsafe:
      implicit unsafe => runtime.unsafe.run(effect).getOrThrow()

  private val tracer = (OpenTelemetry.global >>> OpenTelemetry.tracer("test-app")).orDie

  extension [R, E, A](effect: ZIO[R, E, A])
    private def traced(name: String): ZIO[R, E, A] = (for
      tracer <- ZIO.service[Tracer]
      a <- tracer.span(name)(effect)
    yield a).provideSomeLayer[R](tracer)
```
It works the same regardless of if I use `zio-opentelemetry:4.0.0-RC2` or not (original code snippet). 

Maybe this problem is related to how auto-instrumentation works for zio and does nothing to do with usage of lib `zio-opentelemetry:4.0.0-RC2`?

**Comment by grouzen** [comment]
@seveneves Hi! Thanks for reporting back. 
Sorry, I should have been explicit about it. You need to disable the ZIO instrumentation in `opentelemetry-javaagent` as we did before, because it is still there and messes up the context. 

> The situation is a bit more complex in my app compared to the example I posted. There is also usage of zio.telemetry.opentelemetry.OpenTelemetry.global ++ zio.telemetry.opentelemetry.OpenTelemetry.contextJVM from dev.zio:zio-opentelemetry to have custom traces in zio effects.

I'd appreciate it if you could provide a complete example, including the use of `Opentelemetry.global`. 
Now you need to use `OpenTelemetry.def autoinstrumented[R, E, A](zio: => ZIO[R, E, A])(implicit trace: Trace): ZIO[R, E, A]` to wrap your code to pass the OTEL context provided by opentelemetry-javaagent. 
Hope it makes sense.

**Comment by grouzen** [comment]
Here is my version:
```scala
//> using dep io.opentelemetry.instrumentation:opentelemetry-instrumentation-annotations:2.15.0
//> using dep dev.zio::zio:2.1.17
//> using dep dev.zio::zio-opentelemetry:4.0.0-RC2
//> using scala 3.6.4
//> using javaOpt -Dotel.traces.exporter=console -Dotel.metrics.exporter=none -Dotel.instrumentation.zio.enabled=false -javaagent:<$OTEL_AGENT_PATH>

import io.opentelemetry.api.trace.Span
import zio.*
import zio.telemetry.opentelemetry.OpenTelemetry
import zio.telemetry.opentelemetry.trace.Tracer

object TestApp extends ZIOAppDefault:

  override def run =
    (for {
      otel <- ZIO.service[OpenTelemetry]
      tracer <- ZIO.service[Tracer]
      _ <- ZIO.attempt(unsafe()) @@
        tracer.aspects.span("root") @@
        otel.aspects.autoinstrumented
    } yield ()).provide(OpenTelemetry.global, OpenTelemetry.tracer("test-app"))

  private def unsafe(): Unit =
    println(currentSpan("Before"))
    ZIO.attempt(s"unsafely-executed").unsafeRun
    println(currentSpan("After"))

  private def currentSpan(name: String) =
    val ctx = Span.current().getSpanContext
    s"$name VALID: ${ctx.isValid}, ${ctx.getSpanId}"

  extension [E, A](effect: ZIO[Any, E, A])
    private def unsafeRun(using E <:< Throwable): A = Unsafe.unsafe:
      implicit unsafe => runtime.unsafe.run(effect).getOrThrow()

```
It works.

**Comment by seveneves** [comment]
i will check it with my service. 

thank you for your work!

**Comment by seveneves** [comment]
@grouzen Sorry for a delay. Will provide results soon

**Comment by grouzen** [comment]
No worries. Curious about your experience. Thanks!

**Comment by seveneves** [comment]
@grouzen I can confirm the the specific issue of using Unsafe operation is fixed. I played with the code you provided and it does work correctly. 

However, I still have a problem of linking spans into the same trace for an app based on zio + tapir + zio-telementry version 4.RC2. Each span generated for a single http call has its own trace id, while they should share it. I will explore the issue in depth and try to isolate it, for now it is not clear what lib is responsible for breaking context propagation in more complex setup. 

There is no such issue in the App you shared, where tapir is not used.

I can suggest to close this issue and once I find a culprit for the new one, I will create it in corresponding project. 

Thank you!

**Comment by grouzen** [comment]
@seveneves Thanks for your feedback. I'd like to ask a couple of questions. 
- Do you use the opentelemetry-java agent with your `zio + tapir + zio-telementry` setup? 
- I assume it is some sort of http service since you're using tapir. What http library are you using (http4s/zio-http/etc)? 
- In case you're not using opentelemetry-java agent, you need to pass the context manually via http headers.

**Comment by seveneves** [comment]
@grouzen 

Here is the app to reproduce the problem 


```scala
//> using dep io.opentelemetry.instrumentation:opentelemetry-instrumentation-annotations:2.15.0
//> using dep dev.zio::zio:2.1.17
//> using dep org.slf4j:slf4j-simple:2.0.17
//> using dep com.softwaremill.sttp.tapir::tapir-core:1.11.28
//> using dep com.softwaremill.sttp.tapir::tapir-zio:1.11.28
//> using dep com.softwaremill.sttp.tapir::tapir-netty-server-zio:1.11.28
//> using dep com.softwaremill.sttp.tapir::tapir-opentelemetry-tracing:1.11.28
//> using dep dev.zio::zio-opentelemetry:4.0.0-RC2
//> using scala 3.7.0
//> using javaOpt -Dotel.instrumentation.zio.enabled=false -Dotel.traces.exporter=console -Dotel.metrics.exporter=none -Dotel.logs.exporter=none -javaagent:/Users/xxx/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/io/opentelemetry/javaagent/opentelemetry-javaagent/2.15.0/opentelemetry-javaagent-2.15.0.jar

import io.opentelemetry.api.trace.Span
import sttp.tapir.server.netty.zio.{NettyZioServer, NettyZioServerOptions}
import sttp.tapir.server.tracing.opentelemetry.OpenTelemetryTracing
import sttp.tapir.ztapir.*
import zio.*
import zio.telemetry.opentelemetry.OpenTelemetry
import zio.telemetry.opentelemetry.trace.Tracer

import scala.annotation.nowarn
import scala.util.Try

object TapirApp extends ZIOApp:

  override type Environment = Tracer & OpenTelemetry

  override def environmentTag: zio.EnvironmentTag[Environment] = zio.EnvironmentTag[Environment]

  override def bootstrap: ZLayer[ZIOAppArgs, Any, Environment] = ZLayer
    .make[Environment]
    .apply[Throwable](
      OpenTelemetry.global,
      OpenTelemetry.tracer("test-app"),
    )

  private val helloWorldEndpoint = endpoint.get
    .in("hello" / "world")
    .securityIn(header[String]("X-API-KEY"))
    .out(stringBody)

  @nowarn override def run: ZIO[Environment & ZIOAppArgs & Scope, Any, Any] = for _ <- NettyZioServer[Environment]()
//      .options(NettyZioServerOptions.default[Environment].prependInterceptor(OpenTelemetryTracing(otel.asJava)))
      .addEndpoint(
        helloWorldEndpoint
          .zServerSecurityLogic(s => security(s))
          .serverLogic(sec => _ => handler(s"$sec\n${spanName("serverLogic")}"))
      )
      .port(8081)
      .start()
      .withFinalizer(_.stop().ignore)
      .autoinstrumented
      .flatMap(_ => ZIO.never)
  yield ()

  private def security(h: String) = span("security"):
    for
      _ <- ZIO.unit
      otel <- ZIO.service[OpenTelemetry]
      span1 = spanName("Before Sec")
      _ <- ZIO.fromTry(Try(ZIO.attempt(s"unsafely-executed").unsafeRunTask(otel))).orDie
      span2 = spanName("After Sec")
    yield s"$span1\n$span2\n"
  .autoinstrumented

  private def handler(sec: String) = span("handler"):
    for
      _ <- ZIO.unit
      otel <- ZIO.service[OpenTelemetry]
      span1 = spanName("Before Handler")
      _ <- ZIO.fromTry(Try(ZIO.attempt(s"unsafely-executed").unsafeRunTask(otel))).orDie
      span2 = spanName("After Handler")
    yield s"$sec\n\n$span1\n$span2\n"
  .autoinstrumented

  private def span[R, E, T](name: String)(eff: ZIO[R, E, T]) = for
    tracer <- ZIO.service[Tracer]
    t <- tracer.span(name)(eff)
  yield t

  private def spanName(name: String) =
    val ctx = Span.current().getSpanContext
    s"$name VALID: ${ctx.isValid}, SPAN: ${ctx.getSpanId}, TRACE: ${ctx.getTraceId}"

  extension [A](effect: ZIO[Any, Throwable, A])
    private def unsafeRunTask(otel: OpenTelemetry) = Unsafe.unsafe:
      implicit unsafe => runtime.unsafe.run(effect.autoinstrumented.provide(ZLayer.succeed(otel))).getOrThrow()

  extension [R, E, A](effect: ZIO[R, E, A])
    private def autoinstrumented: ZIO[R & OpenTelemetry, E, A] = for
      otel <- ZIO.service[OpenTelemetry]
      a <- effect @@ otel.aspects.autoinstrumented
    yield a
```

From what I see the `Unsafe` breaks trace propagation and `autoinstrumented` does not seem to help.

I expect that single http call to the server 

```
curl -v --header X-API-KEY:lala  http://127.0.0.1:8081/hello/world
```
should have three spans `GET`, `security` and `handler` and all of them to be linked by a singe trace id. 

This can be achieved only with `-Dotel.instrumentation.zio.enabled=true` and there is no `Unsafe` operation in `security` and `handler` methods. 

All other configurations, ie `-Dotel.instrumentation.zio.enabled=false` or adding `OpenTelemetryTracing`, or removing/adding `otel.aspects.autoinstrumented` did not fix the problem.

**Comment by grouzen** [comment]
@seveneves Thanks. Looking into this. However, I can say right away that this is due to how the tapir is designed. We need to come up with a solution to have auto instrumentation in tapir. 
My current understanding that it should be similar to the existing otel4s instrumentation https://github.com/softwaremill/tapir/blob/master/tracing/otel4s-tracing/src/main/scala/sttp/tapir/server/tracing/otel4s/Otel4sTracing.scala#L54 but instead of `joinOrRoot` we need to use `OpenTelemetry.autoinstrumented` to connect java and zio contexts properly.

Also, in your example, you're calling `.autoinstrumented` many times, which is not how it is supposed to be used. The idea is to call it at the entry point of your application so that the rest of the logic is wrapped in the auto-instrumented context. I hope it makes sense.

**Comment by seveneves** [comment]
@grouzen Really appreciate the level of commitment and the work you put to support this. Thank you!

> The idea is to call it at the entry point of your application so that the rest of the logic is wrapped in the auto-instrumented context

How should it be handled for `Unsafe` invocations? I assume that what you described works well for zio-based app with `run` method defined. However, this is less applicable to code with a lot legacy, which requires `Unsafe` usage.

To understand how `autoinstrumented` should be used, would you recommend adding `autoinstrumented` aspect to the effect that is invoked with `Unsafe`?

----

> but instead of joinOrRoot we need to use OpenTelemetry.autoinstrumented to connect java and zio contexts properly.

I assume the problem is in this method that converts zio effect to a future by using `Unsafe` without context propagation.

https://github.com/softwaremill/tapir/blob/081e8d84f97176bb5081ab8d5181f87c945f8d2e/server/netty-server/zio/src/main/scala/sttp/tapir/server/netty/zio/NettyZioServer.scala#L88

If this is correct then `autoinstrumented` is less of an "auto" and more of "manual" instrumentation. It will be hard to ensure that all `Unsafe` usages also do `autoinstrumented`.

**Comment by grouzen** [comment]
> How should it be handled for Unsafe invocations? I assume that what you described works well for zio-based app with run method defined. However, this is less applicable to code with a lot legacy, which requires Unsafe usage.

I assume you need to embed an unsafe block of code into a ZIO app that can call the OTEL Java SDK to create spans, etc.

In this case, the code must be structured like this:
```
OpenTelemetry.autoinstrumented(
     ...
    tracer.scopedEffect { 
      val jspan = jtracer.spanBuilder().startSpan()
      doSomething()
     jspan.end()
   }
     ...
)
```

> To understand how autoinstrumented should be used, would you recommend adding autoinstrumented aspect to the effect that is invoked with Unsafe?

No, it should be used only once at the entry point.

> I assume the problem is in this method that converts zio effect to a future by using Unsafe without context propagation.

I don't think so, but I'm unfamiliar with the tapir's guts. My idea is that it doesn't matter what's going on on the tapir level because we rely on the ThreadLocal-based ContextStorage mechanism provided by opentelemetry-java and its agent.

I think a module similar to `Otel4sTracing` should solve this problem (aka `RequestInterceptor`). The tracing tapir module for zio-opentelemetry can support both autoinstrumented and manual modes. The former will use `OpenTelemetry.autoinstrumented` + `OpenTelemetry.global`, while for the latter we need to use `OpenTelemetry.continue` + `OpenTelemetry.custom` + an ability to set a desired span name, instrumentation scope and so on.

> If this is correct then autoinstrumented is less of an "auto" and more of "manual" instrumentation. It will be hard to ensure that all Unsafe usages also do autoinstrumented.

No, it is not. I hope this question is answered above. 

Please let me know if you have more questions.

**Comment by grouzen** [comment]
I guess we can close this one and create another issue to add a tapir module instead.
